<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>fce16470-1f05-4bf8-b3e9-5296b0437754</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.20">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PersonalFinance.Identity.Api\PersonalFinance.Identity.Api.csproj" />
    <ProjectReference Include="..\PersonalFinance.Identity.Application\PersonalFinance.Identity.Application.csproj" />
    <ProjectReference Include="..\PersonalFinance.Identity.Domain\PersonalFinance.Identity.Domain.csproj" />
    <ProjectReference Include="..\PersonalFinance.Identity.Infrastructure\PersonalFinance.Identity.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

</Project>
